### ISSUE TITLE
 Compile Flow with Java 11 language features

### ISSUE THREAD

**Issue by caalador** [vaadin/vaadin-date-picker-flow#134]
Fix Flow so it can be compiled with Java 11 language features.

Updated vaadin atmosphere is required: https://oss.sonatype.org/content/repositories/comvaadin-2656 repository is a Staging repository that contains the wanted 2.5.0 version. If it's seen as functioning as expected then it can be released to Maven central.

Java 11 will need the fix for jetty issue 2941.

As now starting Flow with Java11 gives us:
```
	Caused by: java.lang.UnsupportedOperationException
		at org.objectweb.asm.ClassVisitor.visitNestMemberExperimental(ClassVisitor.java:248)
		at org.objectweb.asm.ClassReader.accept(ClassReader.java:651)
		at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
		at org.eclipse.jetty.annotations.AnnotationParser.scanClass(AnnotationParser.java:933)
		at org.eclipse.jetty.annotations.AnnotationParser.parseDir(AnnotationParser.java:737)
		... 6 more
```
And many more.

Also the `DomApiAbstractionUsageTest.java` fails on `Caused by: java.lang.UnsupportedOperationException: This feature requires ASM7` 

Also note that ASM7 is still only 7.0-beta. and we need to have version 7.0 for JDK11

**Comment by web-padawan** [comment]
This does not seem specific to DatePicker. Probably it was supposed to be Flow issue.

Closing, please submit a new issue if needed.
